CLASS_ACRO_MAP = {
    'Paladin': 'PLD',
    'Warrior': 'WAR',
    'DarkKnight': 'DRK',
    'Gunbreaker': 'GNB',
    'Monk': 'MNK',
    'Dragoon': 'DRG',
    'Ninja': 'NIN',
    'Samurai': 'SAM',
    'Reaper': 'RPR',
    'WhiteMage': 'WHM',
    'Scholar': 'SCH',
    'Astrologian': 'AST',
    'Sage': 'SGE',
    'Bard': 'BRD',
    'Machinist': 'MCH',
    'Dancer': 'DNC',
    'BlackMage': 'BLM',
    'Summoner': 'SMN',
    'RedMage': 'RDM',
    'BlueMage': 'BLU'
}